on:
  push:
    branches:
      - master
jobs:
  ssh_deployer:
    runs-on: ubuntu-18.04
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1
        - name: install ssh
          run: |
              sudo apt update
              sudo apt install -y ssh
        - name: Setup key
          run: |
              mkdir -p /home/runner/.ssh
              chmod 700 /home/runner/.ssh
              echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /home/runner/.ssh/config
              echo "${{ secrets.CD_SSH_KEY }}" > /home/runner/.ssh/id_rsa
              cat /home/runner/.ssh/id_rsa
              chmod 600 /home/runner/.ssh/id_rsa
              ssh user@your-server -i /home/runner/.ssh/id_rsa 'ls -la'
